[indexer]

[embeddings]
provider = "localapi"
model = "BAAI/bge-code-v1"
batch_size = 1000
api_base_url = "http://localhost:8000/v1"
embedding_dimension = 1536

[watcher]
debounce_ms = 500
ignore_patterns = [
    "*.log",
    "node_modules",
    "target",
    ".git",
    "*.pyc",
    "__pycache__",
]

[storage]
qdrant_host = "localhost"
qdrant_port = 6334
qdrant_rest_port = 6333
collection_name = "codesearch_2692001907bae15d5a4b45ad9dd260fd"
auto_start_deps = true
postgres_host = "localhost"
postgres_port = 5432
postgres_database = "codesearch"
postgres_user = "codesearch"
postgres_password = "codesearch"

[languages]
enabled = ["rust"]

[languages.python]
preserve_docstrings = true
include_type_hints = true

[languages.javascript]
preserve_jsx = true
typescript_enabled = true
