# Database services for codesearch
# The codesearch CLI runs natively and connects to these containerized services

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: codesearch-qdrant
    ports:
      - "127.0.0.1:6333:6333"  # REST API port - localhost only
      - "127.0.0.1:6334:6334"  # gRPC port - localhost only
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__LOG_LEVEL=INFO
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:6333/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    restart: unless-stopped

volumes:
  qdrant_data:
    driver: local